# Generated by Django 4.1.3 on 2022-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('equipo', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=60)),
                ('posicion', models.CharField(max_length=40)),
            ],
        ),
    ]
